Update Ruby to 3.4.1 (#49)
TravisCI builds started failing because the latest version of RubyGems requires a newer Ruby version that what we use.

$ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update-3.6.3 requires Ruby version >= 3.1.0. The current ruby version is 3.0.0.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .

This PR updates Ruby to the latest version, 3.4.1. Branch build was successful https://app.travis-ci.com/github/SnapLogic/developer.snaplogic.com/builds/274181859.